### PR TITLE
Allow for consumer-defined database retrieval

### PR DESCRIPTION
**Pull request by g-andrade**
Implements #28

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Nice. The linked issue is now closable, too, right?

**Comment by g-andrade** [comment]
Not until I've tagged / released the changes - otherwise someone might easily be mislead into believing they're available.

**Comment by paulo-ferraz-oliveira** [comment]
Oh, I see. Though your reasoning is right, it's not the norm we see out there, which is why I was mislead, here. Fun stuff!

**Comment by g-andrade** [comment]
Yeah, I kind of rationalized it on the spot - the truth is, I've got a bunch of other changes (pushed or otherwise) I'd like include in the next release and it might be a few days before that happens (which is generally not the case.)

**Pull request merged**
